#!/bin/sh
#
# capture in PCAP binary format with minimal filtering
# 
# Wireshark's CLI application: tshark
#
# 	-i <network interface>
#		VPN: utun0, Ethernet: en3, WiFi: en0 ?
# 	-O <protocols>
# 	-f <capture filter>
#		"host <Controller_IP>"
# 	-l flush standard output after each packet
# 	-V add output of packet tree (Packet Details)
# 	-w <outfile>
# 	-q minimize foreground stdout
#

echo
if [ $# -lt 1 ]
then
	echo "Usage: $0 <outputfile[.cap]>"
	echo
	exit 1
fi

# strip any '.*' file extension
fname="${1%.*}"

sudo tshark -i utun0 -V -f "host 10.10.2.93" -l -q -w "$fname".cap 1>/dev/null
